### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by dav1312** [GR0SST/CopyRawEmbed#3]
Typo
https://github.com/GR0SST/CopyRawEmbed/blob/3f87927d2a762a2e4781605af6b2fbe5a711f3d8/CopyRawEmbeds.plugin.js#L199

Old Website
https://github.com/GR0SST/CopyRawEmbed/blob/3f87927d2a762a2e4781605af6b2fbe5a711f3d8/CopyRawEmbeds.plugin.js#L90

**Comment by GR0SST** [comment]
fixed
