### ISSUE TITLE
Why doesn't it work in a web hook?

### ISSUE THREAD

**Issue by joeydoesthings** [GR0SST/CopyRawEmbed#4]
I tried pasting it into discord.club or discohook and it says:

$: Excessive key "footer"
$: Excessive key "timestamp"
$: Excessive key "color"
$: Excessive key "image"
$: Excessive key "description"
$: Excessive key "title"

**Comment by dav1312** [comment]
You have to paste it inside an embed
```json
{
  "content": null,
  "embeds": [
    copied code here
  ]
}
```
